---
name: Subgraph Master Deploy

# Controls when the action will run.
on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      chain:
        description: 'Chain to deploy, e.g. rinkeby or shiden'
        required: true
      subgraphs:
        description: 'Space-separated list of subgraphs to deploy, e.g. exchange or exchange masterchefV2'
        required: true
      graph_hosted:
        description: 'Bool defining if this is deployed to Hosted Graph'
        required: false
        default: true
      graph_url:
        description: 'Graph URL'
        required: false
        default: https://api.thegraph.com/deploy/
      ipfs_url:
        description: 'IPFS URL'
        required: false
        default: https://api.thegraph.com/ipfs/

jobs:
  subgraph-deploy:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - chain: shiden
            subgraphs: exchange masterchefV2 blocks candles
            graph_hosted: false
            graph_url: https://graph.shiden.standardtech.xyz:4443
            ipfs_url: https://api.thegraph.com/ipfs/
    env:
      CHAIN: ${{ github.event_name == 'push' && matrix.chain || github.event.inputs.chain }}
      SUBGRAPHS: ${{ github.event_name == 'push' && matrix.subgraphs || github.event.inputs.subgraphs }}
      GRAPH_HOSTED: ${{ github.event_name == 'push' && matrix.graph_hosted || github.event.inputs.graph_hosted }}
      GRAPH_URL: ${{ github.event_name == 'push' && matrix.graph_url || github.event.inputs.graph_url }}
      IPFS_URL: ${{ github.event_name == 'push' && matrix.ipfs_url || github.event.inputs.ipfs_url }}
      GRAPH_USER: digitalnativeinc
      GRAPH_CLI_VERSION: 0.22.2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Yarn - Restore cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn - Prepare
        shell: bash
        run: |
          yarn install --prefer-offline
          yarn prepare
          yarn codegen

      - name: Yarn - Deploy Subgraph
        shell: bash
        if:
        run: |
          for WORKSPACE in ${{ env.SUBGRAPHS }}; do
            if [[ ${{ matrix.graph_hosted }} == 'false' ]]; then
              yarn workspace $WORKSPACE create-subgraph
              yarn workspace $WORKSPACE deploy --version-label 1.0.1
            else
              yarn workspace $WORKSPACE deploy --access-token ${{ secrets.GRAPH_API_KEY }}
            fi
          done
