---
name: Subgraph Deploy

# Controls when the action will run.
on:
  push:
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GRAPH_USER: digitalnativeinc
  GRAPH_CLI_VERSION: 0.22.2

jobs:
  subgraph-deploy:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - chain: rinkeby
            subgraphs: exchange masterchefV2 blocks erc721 candles
            workspace: exchange
            graph_service: hosted
          - chain: shibuya
            subgraphs: exchange masterchefV2 blocks erc721 candles
            graph_service: private
            graph_url: https://graph.shibuya.standardtech.xyz:4443
            ipfs_url: https://ipfs.shibuya.standardtech.xyz
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Yarn - Restore cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn - Deploy Subgraph
        shell: bash
        env:
          CHAIN: ${{ matrix.chain }}
          GRAPH_URL: ${{ matrix.graph_url }}
          IPFS_URL: ${{ matrix.ipfs_url }}
        run: |
          yarn install --prefer-offline
          yarn prepare
          for WORKSPACE in ${{ matrix.subgraphs }}; do
            yarn workspace $WORKSPACE codegen
            if [ ${{ matrix.graph_service }} -eq 'private' ]; then yarn workspace $WORKSPACE create-subgraph; fi
            yarn workspace ${{ matrix.workspace }} deploy --access-token ${{ secrets.GRAPH_API_KEY }}
            yarn workspace $WORKSPACE deploy
          done
