---
name: Subgraph Deploy

# Controls when the action will run.
on:
  push:
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GRAPH_USER: digitalnativeinc
  GRAPH_CLI_VERSION: 0.22.2

jobs:
  subgraph-deploy:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - chain: rinkeby
            subgraphs: exchange masterchefV2 blocks erc721 candles
            workspace: exchange
            graph_service: hosted
          - chain: shibuya
            subgraphs: exchange masterchefV2 blocks erc721 candles
            graph_service: private
            graph_url: https://graph.shibuya.standardtech.xyz:4443
            ipfs_url: https://ipfs.shibuya.standardtech.xyz
    env:
      CHAIN: ${{ matrix.chain }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Yarn - Restore cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn - Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --prefer-offline

      - name: Yarn - Prepare Subgraph
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: prepare

      - name: Yarn - Subgraph Code Generation
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: codegen

      - name: Yarn - Deploy Subgraph
        shell: bash
        env:
          GRAPH_URL: ${{ matrix.graph_url }}
          IPFS_URL: ${{ matrix.ipfs_url }}
        run: |
          for WORKSPACE in ${{ matrix.subgraphs }}; do
            if [ ${{ matrix.graph_service }} == 'private' ]; then
              yarn workspace $WORKSPACE create-subgraph
              yarn workspace $WORKSPACE deploy
            else
              yarn workspace $WORKSPACE deploy --access-token ${{ secrets.GRAPH_API_KEY }}
            fi
            yarn workspace $WORKSPACE deploy
          done
